apiVersion: v1
kind: ServiceAccount
metadata:
  name: image-resizer-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::436805326321:role/EKSImageResizerRole
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-resizer-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: image-resizer
  template:
    metadata:
      labels:
        app: image-resizer
    spec:
      serviceAccountName: image-resizer-sa
      containers:
      - name: image-resizer
        image: public.ecr.aws/g3a2b0e2/image-resizer:v1
        ports:
        - containerPort: 80
